server:
    port: 8081

spring:
    application:
        name: auth-service
    config:
        import:
            - optional:classpath:.env.properties

jwt:
    access-token-secret: ${ACCESS_TOKEN_SECRET}
    refresh-token-secret: ${REFRESH_TOKEN_SECRET}
    access-token-expire-minutes: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    refresh-token-expire-days: ${REFRESH_TOKEN_EXPIRE_DAYS}

eureka:
    client:
        enabled: true
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true