server:
    port: 8761

spring:
    application:
        name: service-registry

eureka:
    client:
        enabled: true
        fetch-registry: false
        register-with-eureka: false
        healthcheck:
            enabled: true

    instance:
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 10
        lease-expiration-duration-in-seconds: 30
        instance-id: ${spring.application.name}:${random.value}
        status-page-url-path: /management/info
        health-check-url-path: /management/health
        hostname: localhost

    server:
        enable-self-preservation: true